/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as AuthSignupImport } from './routes/auth/signup'
import { Route as AuthSigninImport } from './routes/auth/signin'
import { Route as AuthPasswordResetIndexImport } from './routes/auth/password-reset/index'
import { Route as AuthEmailVerificationIndexImport } from './routes/auth/email-verification/index'
import { Route as AuthPasswordResetTokenImport } from './routes/auth/password-reset/$token'
import { Route as AuthEmailVerificationTokenImport } from './routes/auth/email-verification/$token'

// Create/Update Routes

const AuthSignupRoute = AuthSignupImport.update({
  path: '/auth/signup',
  getParentRoute: () => rootRoute,
} as any)

const AuthSigninRoute = AuthSigninImport.update({
  path: '/auth/signin',
  getParentRoute: () => rootRoute,
} as any)

const AuthPasswordResetIndexRoute = AuthPasswordResetIndexImport.update({
  path: '/auth/password-reset/',
  getParentRoute: () => rootRoute,
} as any)

const AuthEmailVerificationIndexRoute = AuthEmailVerificationIndexImport.update(
  {
    path: '/auth/email-verification/',
    getParentRoute: () => rootRoute,
  } as any,
)

const AuthPasswordResetTokenRoute = AuthPasswordResetTokenImport.update({
  path: '/auth/password-reset/$token',
  getParentRoute: () => rootRoute,
} as any)

const AuthEmailVerificationTokenRoute = AuthEmailVerificationTokenImport.update(
  {
    path: '/auth/email-verification/$token',
    getParentRoute: () => rootRoute,
  } as any,
)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth/signin': {
      id: '/auth/signin'
      path: '/auth/signin'
      fullPath: '/auth/signin'
      preLoaderRoute: typeof AuthSigninImport
      parentRoute: typeof rootRoute
    }
    '/auth/signup': {
      id: '/auth/signup'
      path: '/auth/signup'
      fullPath: '/auth/signup'
      preLoaderRoute: typeof AuthSignupImport
      parentRoute: typeof rootRoute
    }
    '/auth/email-verification/$token': {
      id: '/auth/email-verification/$token'
      path: '/auth/email-verification/$token'
      fullPath: '/auth/email-verification/$token'
      preLoaderRoute: typeof AuthEmailVerificationTokenImport
      parentRoute: typeof rootRoute
    }
    '/auth/password-reset/$token': {
      id: '/auth/password-reset/$token'
      path: '/auth/password-reset/$token'
      fullPath: '/auth/password-reset/$token'
      preLoaderRoute: typeof AuthPasswordResetTokenImport
      parentRoute: typeof rootRoute
    }
    '/auth/email-verification/': {
      id: '/auth/email-verification/'
      path: '/auth/email-verification/'
      fullPath: '/auth/email-verification/'
      preLoaderRoute: typeof AuthEmailVerificationIndexImport
      parentRoute: typeof rootRoute
    }
    '/auth/password-reset/': {
      id: '/auth/password-reset/'
      path: '/auth/password-reset/'
      fullPath: '/auth/password-reset/'
      preLoaderRoute: typeof AuthPasswordResetIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  AuthSigninRoute,
  AuthSignupRoute,
  AuthEmailVerificationTokenRoute,
  AuthPasswordResetTokenRoute,
  AuthEmailVerificationIndexRoute,
  AuthPasswordResetIndexRoute,
})

/* prettier-ignore-end */
